/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControllerPinjam;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelPinjam;
import util.Koneksi;

/**
 *
 * 
 */
public class ViewPinjam extends javax.swing.JPanel {

    ControllerPinjam cp = new ControllerPinjam();
    ModelPinjam mp = new ModelPinjam();
    Koneksi kon = new Koneksi();
    String query = "";
    /**
     * Creates new form ViewPinjam1
     */
    public ViewPinjam() {
        initComponents();
        firstInit();
    }

    void firstInit(){
        Baru.setVisible(true);
        Baru.setEnabled(true);
        Batal.setVisible(false);
        Bersih.setEnabled(false);
        butCari.setEnabled(false);
        Simpan.setEnabled(false);
        Ubah.setEnabled(false);
        Hapus.setEnabled(false);
        Tutup.setEnabled(true);
        texID.setEditable(false);
        texNama.setEditable(false);
        texBarang.setEditable(false);
    }
    
    void buttonBaru(){
        Baru.setVisible(false);
        Batal.setVisible(true);
        Simpan.setEnabled(true);
        texID.setEditable(true);
        texNama.setEditable(true);
        texBarang.setEditable(true);
        butCari.setEnabled(true);
    }
    
    void tampilData(){
        query = "select * from tbl_pinjam";
        try {
            kon.getConnection();
            ResultSet rs = kon.state.executeQuery(query);
            while(rs.next()){
                dtm.addRow(new Object[]{
                    rs.getString("ID"),
                    rs.getString("namaTeman"),
                    rs.getString("barangDipinjam")
                });
            }
            Tabel.setModel(dtm);
            kon.state.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "terjadi kesalahan");
            System.err.println(e.getMessage());
        }
    }
    
    void buttonEdit(){
        Baru.setVisible(false);
        Batal.setVisible(true);
        Simpan.setEnabled(false);
        texID.setEditable(true);
        texNama.setEditable(true);
        texBarang.setEditable(true);
        Bersih.setEnabled(true);
        butCari.setEnabled(true);
        Ubah.setEnabled(true);
        Hapus.setEnabled(true);
    }
    /**
     * This method is called from within the konekstructor to initialize the form.
     * WARNING: Do NOT modify this code. The konektent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        texID = new javax.swing.JTextField();
        texNama = new javax.swing.JTextField();
        NAMA = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texBarang = new javax.swing.JTextArea();
        butCari = new javax.swing.JButton();
        Baru = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Bersih = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Tutup = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nama");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        add(texID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 76, -1));
        add(texNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 201, -1));

        add(NAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 201, -1));

        jLabel3.setText("Barang");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        texBarang.setColumns(20);
        texBarang.setRows(5);
        jScrollPane1.setViewportView(texBarang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 385, 60));

        butCari.setText("Cari");
        butCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCariActionPerformed(evt);
            }
        });
        add(butCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        Baru.setText("Baru");
        Baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaruActionPerformed(evt);
            }
        });
        add(Baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        Bersih.setText("Bersih");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });
        add(Bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        Tutup.setText("Tutup");
        Tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutupActionPerformed(evt);
            }
        });
        add(Tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama Teman ", "Barang Dipinjam"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 440, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void butCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCariActionPerformed
        // TODO add your handling code here:
        query = "select * from tbl_teman where nama like '%"+texNama.getText()+"%'";
        try {
            kon.getConnection();
            NAMA.removeAllItems();
            ResultSet rs = kon.state.executeQuery(query);
            while(rs.next()){
                NAMA.addItem(rs.getString("nama"));
            }
            kon.state.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "terjadi kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_butCariActionPerformed

    private void BaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaruActionPerformed
        // TODO add your handling code here:
        buttonBaru();
        texNama.requestFocus();
    }//GEN-LAST:event_BaruActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        if(NAMA.getSelectedItem().equals("") || texBarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Masukkan Data Dengan Benar", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            texNama.requestFocus();
        }else{
            if(JOptionPane.showConfirmDialog(this, "Apakah anda ingin menyimpan data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION)==0){
                try {
                    mp.setNama(NAMA.getSelectedItem().toString());
                    mp.setBarang(texBarang.getText());
                    cp.SimpanData(mp);
                    dtm.getDataVector().removeAllElements();
                    tampilData();
                    bersih();
                    firstInit();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "terjadi kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
                    System.err.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_SimpanActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_BersihActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "apakah anda ingin mengubah data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION)==0){
            try {
                mp.setId(Integer.parseInt(texID.getText()));
                mp.setNama(NAMA.getSelectedItem().toString());
                mp.setBarang(texBarang.getText());
                cp.UbahData(mp);
                dtm.getDataVector().removeAllElements();
                tampilData();
                bersih();
                firstInit();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "terjadi kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
                System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_UbahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "apakah anda ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION)==0){
            try {
                mp.setId(Integer.parseInt(texID.getText()));
                cp.HapusData(mp);
                dtm.getDataVector().removeAllElements();
                tampilData();
                bersih();
                firstInit();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "terjadi kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
                System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_TutupActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        baris = Tabel.getRowCount();
        texID.setText(Tabel.getValueAt(baris, 0).toString());
        NAMA.setSelectedItem(Tabel.getValueAt(baris, 1).toString());
        texBarang.setText(Tabel.getValueAt(baris, 2).toString());
        buttonEdit();
    }//GEN-LAST:event_TabelMouseClicked

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
        firstInit();
    }//GEN-LAST:event_BatalActionPerformed

    void bersih(){
        texID.setText("");
        texNama.setText("");
        texBarang.setText("");
        NAMA.setSelectedItem("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baru;
    private javax.swing.JButton Batal;
    private javax.swing.JButton Bersih;
    private javax.swing.JButton Hapus;
    private javax.swing.JComboBox NAMA;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Tabel;
    private javax.swing.JButton Tutup;
    private javax.swing.JButton Ubah;
    private javax.swing.JButton butCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea texBarang;
    private javax.swing.JTextField texID;
    private javax.swing.JTextField texNama;
    // End of variables declaration//GEN-END:variables

    int baris = 0;
    static Object[] kolom = {"ID", "Nama", "Barang Dipinjam"};
    DefaultTableModel dtm = new DefaultTableModel(kolom, baris);
}
