/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.table.DefaultTableModel;
import util.Koneksi;
import model.ModelTeman;
import controller.ControllerTeman;
import java.awt.event.ActionListener;
import java.awt.event.ComponentListener;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author abyssBerserker
 */
public class ViewTeman11 extends javax.swing.JPanel implements ActionListener, ComponentListener, MouseListener {

    ControllerTeman ct = new ControllerTeman();
    ModelTeman mt = new ModelTeman();
    Koneksi konek = new Koneksi();
    String query = "";
    /**
     * Creates new form ViewTeman
     */
    public ViewTeman11() {
        initComponents();
        firstIntial();
        tampilTeman();
    }

    void firstIntial(){
        btBaru.setVisible(true);
        btBatal.setVisible(false);
        btBaru.setEnabled(true);
        btSimpan.setEnabled(false);
        btBersih.setEnabled(false);
        btUbah.setEnabled(false);
        btHapus.setEnabled(false);
        btTutup.setEnabled(true);
        txtID.setEditable(false);
        txtNama.setEditable(false);
        txtNope.setEditable(false);
        txtEmail.setEditable(false);
    }
    
    void btBaru(){
        btBaru.setVisible(false);
        btBaru.setEnabled(false);
        btBatal.setVisible(true);
        btBatal.setVisible(true);
        btSimpan.setEnabled(true);
        btBersih.setEnabled(true);
        btUbah.setEnabled(true);
        btHapus.setEnabled(true);
        btTutup.setEnabled(true);
        txtNama.setEditable(true);
        txtNope.setEditable(true);
        txtEmail.setEditable(true);
    }
    void tampilTeman(){
        try {
            query = "select * from tbl_teman";
            konek.getConnection();
            ResultSet rs = konek.st.executeQuery(query);
            while(rs.next()){
                dtm.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nama"),
                    rs.getString("nope"),
                    rs.getString("email")
                });
            }
            tb_viewTeman.setModel(dtm);
            konek.st.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNope = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btBatal = new javax.swing.JButton();
        btSimpan = new javax.swing.JButton();
        btBersih = new javax.swing.JButton();
        btUbah = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_viewTeman = new javax.swing.JTable();
        btBaru = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID :");
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 14, 78, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nama :");
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, 78, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("No. Hp :");
        jLabel3.setName("jLabel3"); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 66, 78, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email :");
        jLabel4.setName("jLabel4"); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 92, 78, -1));

        txtID.setName("txtID"); // NOI18N
        txtID.addComponentListener(this);
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, 40, -1));

        txtNama.setName("txtNama"); // NOI18N
        add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 37, 144, -1));

        txtNope.setName("txtNope"); // NOI18N
        add(txtNope, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 63, 144, -1));

        txtEmail.setName("txtEmail"); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 89, 144, -1));

        btBatal.setText("Batal");
        btBatal.setName("btBatal"); // NOI18N
        btBatal.addActionListener(this);
        add(btBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 67, -1));

        btSimpan.setText("Simpan");
        btSimpan.setName("btSimpan"); // NOI18N
        btSimpan.addActionListener(this);
        add(btSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 48, -1, -1));

        btBersih.setText("Bersih");
        btBersih.setName("btBersih"); // NOI18N
        btBersih.addActionListener(this);
        add(btBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 77, 67, -1));

        btUbah.setText("Ubah");
        btUbah.setName("btUbah"); // NOI18N
        btUbah.addActionListener(this);
        add(btUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 19, 63, -1));

        btHapus.setText("Hapus");
        btHapus.setName("btHapus"); // NOI18N
        btHapus.addActionListener(this);
        add(btHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 48, -1, -1));

        btTutup.setText("Tutup");
        btTutup.setName("btTutup"); // NOI18N
        btTutup.addActionListener(this);
        add(btTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 77, 63, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tb_viewTeman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "No Handphone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_viewTeman.setName("tb_viewTeman"); // NOI18N
        tb_viewTeman.addMouseListener(this);
        jScrollPane1.setViewportView(tb_viewTeman);
        if (tb_viewTeman.getColumnModel().getColumnCount() > 0) {
            tb_viewTeman.getColumnModel().getColumn(0).setResizable(false);
            tb_viewTeman.getColumnModel().getColumn(1).setResizable(false);
            tb_viewTeman.getColumnModel().getColumn(2).setResizable(false);
            tb_viewTeman.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 432, 250));

        btBaru.setText("Baru");
        btBaru.setName("btBaru"); // NOI18N
        btBaru.addActionListener(this);
        add(btBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 19, 67, -1));
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btBatal) {
            ViewTeman11.this.btBatalActionPerformed(evt);
        }
        else if (evt.getSource() == btSimpan) {
            ViewTeman11.this.btSimpanActionPerformed(evt);
        }
        else if (evt.getSource() == btBersih) {
            ViewTeman11.this.btBersihActionPerformed(evt);
        }
        else if (evt.getSource() == btUbah) {
            ViewTeman11.this.btUbahActionPerformed(evt);
        }
        else if (evt.getSource() == btHapus) {
            ViewTeman11.this.btHapusActionPerformed(evt);
        }
        else if (evt.getSource() == btTutup) {
            ViewTeman11.this.btTutupActionPerformed(evt);
        }
        else if (evt.getSource() == btBaru) {
            ViewTeman11.this.btBaruActionPerformed(evt);
        }
    }

    public void componentHidden(java.awt.event.ComponentEvent evt) {
    }

    public void componentMoved(java.awt.event.ComponentEvent evt) {
    }

    public void componentResized(java.awt.event.ComponentEvent evt) {
    }

    public void componentShown(java.awt.event.ComponentEvent evt) {
        if (evt.getSource() == txtID) {
            ViewTeman11.this.txtIDComponentShown(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == tb_viewTeman) {
            ViewTeman11.this.tb_viewTemanMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        // TODO add your handling code here:
        firstIntial();
        Bersih();
    }//GEN-LAST:event_btBatalActionPerformed

    private void btBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBaruActionPerformed
        // TODO add your handling code here:
        btBaru();
        Bersih();
        txtNama.requestFocus();
    }//GEN-LAST:event_btBaruActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNama.getText().isEmpty() || txtNope.getText().isEmpty() || txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Masukkan Data Dengan Benar", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtNama.requestFocus();
        }else{
            if(JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Menyimpan Data ?", "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION)== 0){
                mt.setNama(txtNama.getText());
                mt.setNope(txtNope.getText());
                mt.setEmail(txtEmail.getText());
                try {
                    ct.SimpanData(mt);
                    dtm.getDataVector().removeAllElements();
                    tampilTeman();
                    firstIntial();
                    Bersih();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Terjadi Kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
                    System.err.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void txtIDComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtIDComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDComponentShown

    private void btBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBersihActionPerformed
        // TODO add your handling code here:
        Bersih();
    }//GEN-LAST:event_btBersihActionPerformed

    private void tb_viewTemanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_viewTemanMouseClicked
        // TODO add your handling code here:
        baris = tb_viewTeman.getSelectedRow();
        txtID.setText(tb_viewTeman.getValueAt(baris, 0).toString());
        txtNama.setText(tb_viewTeman.getValueAt(baris, 1).toString());
        txtNope.setText(tb_viewTeman.getValueAt(baris, 2).toString());
        txtEmail.setText(tb_viewTeman.getValueAt(baris, 3).toString());
        btBaru();
    }//GEN-LAST:event_tb_viewTemanMouseClicked

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Mengubah Data ?", "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION)== 0){
            mt.setId(Integer.parseInt(txtID.getText()));
            mt.setNama(txtNama.getText());
            mt.setNope(txtNope.getText());
            mt.setEmail(txtEmail.getText());
            try {
                ct.UbahData(mt);
                dtm.getDataVector().removeAllElements();
                tampilTeman();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
                System.err.println(e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btUbahActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Menghapus Data ?", "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION)== 0){
            mt.setId(Integer.parseInt(txtID.getText()));
            try {
                ct.HapusData(mt);
                dtm.getDataVector().removeAllElements();
                tampilTeman();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan", "Informasi", JOptionPane.ERROR_MESSAGE);
                System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void btTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btTutupActionPerformed

    void Bersih(){
        txtID.setText("");
        txtNama.setText("");
        txtNope.setText("");
        txtEmail.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBaru;
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btBersih;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTutup;
    private javax.swing.JButton btUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_viewTeman;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNope;
    // End of variables declaration//GEN-END:variables

    int baris = 0;
    static Object[] kolom = {"ID", "Nama", "No Handphone", "Email"};
    DefaultTableModel dtm = new DefaultTableModel(kolom, baris);
}
